version: '3.8'

services:
  mysql_test:
    image: mysql:8.0.41-debian
    container_name: realtime_chat_app_mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: chat_app_db_test
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_realtime-chat-test-data:/var/lib/mysql
    networks:
      - chat_app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ptoai20102002"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_test:
    image: redis:8.0-rc1
    container_name: realtime_chat_app_redis_test
    ports:
      - "6380:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - chat_app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "toai20102002", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_realtime-chat-test-data:

networks:
  chat_app_network:
    name: chat_app_network
    driver: bridge