services:
  mysql-test:
    image: mysql:8.0.41-debian
    container_name: realtime_chat_app_mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: gochat_test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3307:3306"  # Different port to avoid conflicts
    networks:
      - chat_app_test_network
    restart: "no"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ptestpassword"]
      interval: 10s
      timeout: 5s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis-test:
    image: redis:8.0-rc1
    container_name: realtime_chat_app_redis_test
    ports:
      - "6380:6379"  # Different port to avoid conflicts
    networks:
      - chat_app_test_network
    restart: "no"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  chat_app_test_network:
    driver: bridge

volumes:
  mysql_test_data:
