services:
  mysql-test:
    image: mysql:8.0.41-debian
    container_name: realtime_chat_app_mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: gochat_test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3307:3306"  # Different port to avoid conflicts
    networks:
      - chat_app_test_network
    restart: "no"
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=128M --innodb-log-file-size=64M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ptestpassword"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis-test:
    image: redis:7.2.4-alpine  # Stable version as fallback
    container_name: realtime_chat_app_redis_test
    ports:
      - "6380:6379"  # Different port to avoid conflicts
    networks:
      - chat_app_test_network
    restart: "no"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  chat_app_test_network:
    driver: bridge
