version: '3.8'

services:
  mysql:
    image: mysql:8.0.41-debian
    container_name: realtime_chat_app_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_realtime-chat-data:/var/lib/mysql
    networks:
      - chat_app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  redis:
    image: redis:8.0-rc1
    container_name: realtime_chat_app_redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - chat_app_network
    restart: unless-stopped
    
volumes:
  mysql_realtime-chat-data:

networks:
  chat_app_network:
    driver: bridge
